const { Router } = require("express");
const article = require("../models/Article");
const category = require("../models/Category");
const user = require("../models/User");
const music = require("../models/Music");
const musicCategory = require("../models/MusicCategory");
const tv = require("../models/Tv");
const tvCategory = require("../models/TvCategory");
const radio = require("../models/Radio");
const radioCategory = require("../models/RadioCategory");
const verse = require('../models/Verse');
const { verifyToken } = require("../middleware/verifyToken");
const upload = require('../middleware/upload');

const router = Router();

router.get("/users", user.getAllUsers);
router.get("/news", article.getAllArticles);
router.post("/news/upload", upload.single('image'), article.upload);
router.get("/categories", category.getCategories);
router.get("/categories/total", category.getTotaCategories);
router.get("/group-categories", category.getCategoriesByGroup);
router.post("/new-article", verifyToken, article.createArticle);
router.post("/new-category", category.createCategory);
router.post("/new-user", user.createUser);
router.get("/news/:newsId", article.getArticle);
router.delete("/news/:articleId", verifyToken, article.deleteArticle);
router.get("/news/stats/total", article.getTotalArticles);
router.get("/news/stats/total-pending", article.getTotalPendingArticles);
// router.get("/news/stats/total-views", article.getTotalViews);
// router.get("/news/stats/most-read", article.getMostRead);
router.get("/news/stats/recent", article.getRecentArticles);
router.post("/signin", user.signinUser);
router.patch("/user/:userId", verifyToken, user.changeRole);
router.get("/users/total", verifyToken, user.getTotalUsers);
router.patch("/edit-article/:articleId", verifyToken, article.editArticle);
router.post("/musics", verifyToken, music.createLibrary);
router.get("/musics", music.getAllMusics);
router.patch("/musics/:id", verifyToken, music.editmusic);
router.post("/musics/categories", verifyToken, musicCategory.createCategory);
router.get("/musics/categories", musicCategory.getCategories);
router.get("/musics/categories/group", musicCategory.getCategoriesByGroup);
router.post("/musics/upload", upload.single('music'), music.upload);
router.post("/musics/cover", upload.single('image'), music.upload);
router.post("/radio", verifyToken, radio.createRadio);
router.get("/radio", radio.getAllRadio);
router.patch("/radio/:id", verifyToken, radio.editRadio);
router.post("/radio/categories", verifyToken, radioCategory.createCategory);
router.get("/radio/categories", radioCategory.getCategories);
router.get("/radio/categories/group", radioCategory.getCategoriesByGroup);
router.post("/radio/upload", upload.single('radio'), radio.upload);
router.post("/radio/cover", upload.single('image'), radio.upload);
router.post("/tv", verifyToken, tv.createTv);
router.get("/tv", tv.getAllTvShows);
router.patch("/tv/:id", verifyToken, tv.editTv);
router.post("/tv/categories", verifyToken, tvCategory.createCategory);
router.get("/tv/categories", tvCategory.getCategories);
router.get("/tv/categories/group", tvCategory.getCategoriesByGroup);
router.post("/tv/upload", upload.single('tv'), tv.upload);
router.post("/tv/cover", upload.single('image'), tv.upload);
router.post("/verses", verse.createVerse);
router.get("/verses", verse.getAllVerses);
router.get("/verses/:verseId", verse.getSingleVerse);
router.patch("/verses/:verseId", verse.editVerse);
router.delete("/verses/:verseId", verse.deleteVerse);
router.post("/comments", verse.createVerse);
router.get("/comments", verse.getAllVerses);
router.get("/comments/:commentId", verse.getSingleVerse);
router.delete("/comments/:commentId", verse.deleteVerse);

module.exports = router;
